"""empty message

Revision ID: a9a76f17e7f6
Revises: 
Create Date: 2021-06-20 12:29:32.433964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a76f17e7f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('developers',
    sa.Column('developer_id', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('developer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developers')
    op.drop_table('teams')
    # ### end Alembic commands ###
